CREATE TABLE "assets" (
	"_id" serial PRIMARY KEY NOT NULL,
	"id" text NOT NULL,
	"symbol" text NOT NULL,
	"name" text NOT NULL,
	"__v" integer DEFAULT 0,
	"current_price" real NOT NULL,
	"price_change_24h" real NOT NULL,
	"price_change_percentage_24h" real NOT NULL,
	"price_change_percentage_24h_in_currency" real NOT NULL,
	"price_change_percentage_1h_in_currency" real NOT NULL,
	"price_change_percentage_7d_in_currency" real NOT NULL,
	"price_change_percentage_30d_in_currency" real NOT NULL,
	"price_change_percentage_1y_in_currency" real NOT NULL,
	"high_24h" real NOT NULL,
	"low_24h" real NOT NULL,
	"ath" real NOT NULL,
	"ath_change_percentage" real NOT NULL,
	"ath_date" timestamp NOT NULL,
	"atl" real NOT NULL,
	"atl_change_percentage" real NOT NULL,
	"atl_date" timestamp NOT NULL,
	"market_cap" real NOT NULL,
	"market_cap_rank" integer NOT NULL,
	"market_cap_change_24h" real NOT NULL,
	"market_cap_change_percentage_24h" real NOT NULL,
	"fully_diluted_valuation" real NOT NULL,
	"total_volume" real NOT NULL,
	"circulating_supply" real NOT NULL,
	"total_supply" real NOT NULL,
	"max_supply" real,
	"roi" jsonb,
	"sparkline_in_7d" jsonb NOT NULL,
	"image" text NOT NULL,
	"messari_id" text,
	"messari_category" text,
	"messari_sector" text,
	"messari_tags" jsonb,
	"classification_ids" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_updated" timestamp NOT NULL,
	CONSTRAINT "assets_id_unique" UNIQUE("id")
);
